require:
  - rubocop-rspec
inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - config/**/*

Style/Documentation:
  Exclude:
    - db/migrate/*

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
