source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'rails', '~> 6.1.1'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'bcrypt', '~> 3.1.7'
gem 'rack-cors'

gem 'mysql2', '~> 0.5'
gem "redis-actionpack"

group :development, :test do
  gem "pry-byebug"
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end
