source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

# base
gem "bcrypt", "~> 3.1.7"
gem "bootsnap", ">= 1.4.4", require: false
gem "puma", "~> 5.0"
gem "rack-cors"
gem "rails", "~> 6.1.1"

# middleware
gem "mysql2", "~> 0.5"
gem "redis-actionpack"

gem "warden"

group :development, :test do
  gem "committee"
  gem "pry-byebug"
  gem "ricecream"

  gem "rspec-rails"
  gem "spring-commands-rspec"
end

group :development do
  gem "annotate"
  gem "listen", "~> 3.3"
  gem "rubocop-github", github: "github/rubocop-github"
  gem "rubocop-rspec", require: false
  gem "spring"
end
