version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID:
        USER_GID:
    init: true
    volumes:
      - ..:/workspace:cached
      - bundle:/usr/local/bundle
    command: sleep infinity 
    ports:
      - 5000:5000
      - 35729:35729
    environment:
      - RAILS_ENV=development
      - RAILS_DB_HOST=db
      - RAILS_DB_PORT=3306
      - RAILS_DB_DATABASE=app
      - RAILS_DB_USERNAME=root
      - RAILS_DB_PASSWORD=''
      - RAILS_REDIS_HOST=redis
      - RAILS_REDIS_PORT=6379
      - RAILS_SECRET_KEY_BASE=''

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:6

volumes:
  bundle:
  db:
