version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: $UID
        USER_GID: $GID
    init: true
    volumes:
      - ..:/workspace:cached
      - bundle:/usr/local/bundle
    command: sleep infinity 
volumes:
  bundle:
